routes/web.php
<?php


//====================================================================================
//
//  ##      ##  #####  #####         #####     #####   ##   ##  ######  #####   ####
//  ##      ##  ##     ##  ##        ##  ##   ##   ##  ##   ##    ##    ##     ##
//  ##  ##  ##  #####  #####         #####    ##   ##  ##   ##    ##    #####   ###
//  ##  ##  ##  ##     ##  ##        ##  ##   ##   ##  ##   ##    ##    ##        ##
//   ###  ###   #####  #####         ##   ##   #####    #####     ##    #####  ####
//
//====================================================================================



//=======================================================
//
//   ####    ###    #####    #####  #####  #####    ##  ##
//  ##      ## ##   ##  ##   ##     ##     ##  ##   ## ##
//  ##     ##   ##  #####    #####  #####  #####    ####
//  ##     #######  ##  ##   ##     ##     ##  ##   ## ##
//   ####  ##   ##  ##   ##  #####  #####  ##   ##  ##  ##
//
//=========================================================




Route::get('/', 'Website\HomeController@index');

Route::resource('contact', 'Website\ContactController');

Route::get('/about', 'Website\HomeController@about');

Route::resource('blog', 'Website\BlogController');

Route::resource('job', 'Website\JobController');

Route::resource('profile', 'Website\ProfileController')->middleware(['auth', 'Student']);

Route::get('\profile/changePassword', function() {


    dd('this is right');
});

Route::get('/profile@changePassword', 'Website\ProfileController@changPassword')->middleware(['auth', 'Student']);

Route::resource('candidates', 'Website\CandidatesController');

Route::resource('company', 'Website\CompanyController');

Route::resource('category', 'Website\CategoryController');

Route::resource('apply', 'Website\ApplyController')->middleware(['auth', 'Student']);

Route::post('search', 'Website\ApplyController@search')->name('search');

Route::resource('comment', 'Website\CommentController');

Auth::routes();

app/Jobs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Category;
use App\Company;

class Jobs extends Model
{

    protected $guarded = [];


    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Dashboard/JobsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs;
use App\Category;
use App\Company;

class JobsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jobs = Jobs::latest()->get();

        return view('admin.jobs.index', compact('jobs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::latest()->get();

        $companies = Company::latest()->get();

        return view('admin.jobs.create', compact('categories', 'companies'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'title'      => 'required|string | min:5',
            'position'   => 'required|string',
            'experience' => 'required|string',
            'avatar'     => 'required',
            'body'       => 'required|min:50|string'

        ]);


        $input = $request->all();

        $file = $request->file('avatar');

       if($file){

        $fileName = $file->getClientOriginalName();

        $fileName = uniqid() . $fileName;

        $file->move('images/', $fileName);

        $input['avatar'] = $fileName;

       }

       $job_data = $request->except(['avatar']);

       $job_data['avatar'] = $fileName;

       $user = Jobs::create($job_data);

       session()->flash('message', 'Job Added Successfully');

       return redirect('dashboard/jobs');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $job = Jobs::findOrFail($id);

        $categories = Category::latest()->get();

        $companies = Company::latest()->get();

        return view('admin.jobs.edit', compact('categories', 'companies', 'job'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
     
        $job = Jobs::findOrFail($id);

        $request->validate([

            'title'      => 'required|string | min:5',
            'position'   => 'required|string',
            'experience' => 'required|string',
            'body'       => 'required|min:50|string'
    
        ]);
    

        $input = $request->all();

        $file = $request->file('avatar');

       if($file){
          
        $fileName = $file->getClientOriginalName();

        $fileName = uniqid() . $fileName;

        $file->move('images/', $fileName);
        
        $input['avatar'] = $fileName;

       }else {

        $input['avatar'] = $job->avatar;

       }
       

       $job->update($input);

       session()->flash('message', 'Job Updated Successfully');

       return redirect('dashboard/jobs');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Jobs::findOrFail($id)->delete();
        
        session()->flash('message', 'Job Deleted Successfully');
 
        return redirect('dashboard/jobs');
    }
}

app/Http/Controllers/Website/ApplyController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Apply;
use Auth;
use App\Jobs;

class ApplyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'job_id'     => 'required|integer',
        ]);

        $data = $request->all();

        $data['user_id'] = Auth::user()->id;

        $exist = Apply::where([
            ['job_id', '=', $request->job_id],
            ['user_id', '=', $data['user_id']]
            
            ])->count();

        if($exist > 0){

            
       session()->flash('message', 'Job Already Applied');

       return redirect('job');

        }else{

        Apply::create($data);

        session()->flash('message', 'You Applied For The Job');

        return redirect('job');

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


public function search(Request $request) {

   $location = $request->search;

   $jobs = Jobs::where('title', '=',  $location);

  return view('website.search', compact('jobs'));




//   if(!empty($request->search)){
//     $searchFields = ['title','content','author_name','category_name'];
//     $query->where(function($query) use($request, $searchFields){
//       $searchWildcard = '%' . $request->search . '%';
//       foreach($searchFields as $field){
//         $query->orWhere($field, 'LIKE', $searchWildcard);
//       }
//     });
//   }




}

}

app/Http/Controllers/Website/BlogController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Blog;
use App\Comments;
class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::latest()->paginate(9);

        return view('website.blog.index', compact("blogs"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $recents = Blog::where('id', '!=', $id)->get();

        $blog = Blog::findOrFail($id);

        $comments = Comments::where('blog_id', $id)->get();

        return view('website.blog.show', compact("blog", "recents", 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Website/CandidatesController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Auth;
class CandidatesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
$students = User::where('role_id', '2')->latest()->paginate(8);;

return view('website.students.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $user = User::findOrFail($id);

        return view('website.students.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

app/Http/Controllers/Website/CategoryController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
use App\Jobs;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->paginate(16);;


        return view('website.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findOrFail($id);

        return view('website.category.show', compact('category'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Website/CommentController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Notifications\newComment;
use App\User;
use Illuminate\Support\Facades\Auth;
use App\Comments;
class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // $user = User::find(1);

        // $user->notify(new newComment);
        $request->validate([

        'blog_id'     => 'required',
    ]);


    $input = $request->all();


   $user = Auth::user()->id;

   $comment = Comments::create([

    'blog_id' => $request['blog_id'],
    'user_id' => $user,
    'body' => $request['body']

   ]);

   session()->flash('message', 'Comment Added Successfully');

   return redirect()->back();



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/website/jobs/index.blade.php
@extends('layouts.website')

@section('content')
	<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url(images/resource/mslider1.jpg) repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax"></div><!-- PARALLAX BACKGROUND IMAGE -->
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header wform">
							<div class="job-search-sec">
								<div class="job-search">
                                    <h4>Explore Available Jobs </h4>
                                </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="block">
			<div class="container">
				 <div class="row">
				 	<div class="col-lg-12">
				 		<div class="job-grid-sec">
							<div class="row">

                                    @forelse ($jobs as $job)

                                    <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                                        <div class="job-grid">
                                            <div class="job-title-sec">
                                                <div class="c-logo"> <img src="{{ asset('/images/' . $job->avatar ) }}" alt=""> </div>
                                                <h3><a href="#" title="">{{ $job->title }}</a></h3>
                                                <span>{{ $job->company->title }}</span>
                                                {{--  <span class="fav-job"><i class="la la-heart-o"></i></span>  --}}
                                            </div>
                                            <span class="job-lctn">{{ $job->company->location }}</span>
                                            <a href="{{ route('job.show', $job->id) }}" title="">APPLY NOW</a>
                                        </div>
                                    </div>

                                    @empty
                                        <h5 style="margin: 100px auto;color: red;font-size: 29px;font-weight: bold;letter-spacing: 3px;" class=" text-center"> No Jobs Yet </h5>
                                    @endforelse
							</div>
						</div>
					 </div>
					 <div class="col-md-12">
							{{$jobs->links()}}
</div>
		
				 </div>
			</div>
		</div>
	</section>

@endsection()

resources/views/website/jobs/show.blade.php
@extends('layouts.website')

@section('content')

	<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url({{ asset('/images/resource/mslider1.jpg') }} ) repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax"></div><!-- PARALLAX BACKGROUND IMAGE -->
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header">
							<h3>Careerk Jobs</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="block">
			<div class="container">
				<div class="row">
				 	<div class="col-lg-8 column">
				 		<div class="job-single-sec">
				 			<div class="job-single-head2">
				 			 <div class="job-title2">
                                    <img src="{{ asset('images/' . $job->avatar) }}" alt="" style="max-width: 100px;float: left;margin-right: 10px;border-radius: 50%;height: 100px;width: 100px;margin-top: -42px;">
                                <h3>{{ $job->title }}</h3><span class="job-is ft">@if($job->type == 1)  Full Time @elseif($job->type == 2) Part Time  @elseif($job->type == 3) Freelance @elseif($job->type == 4) Internship @endif</span>
				 				<ul class="tags-jobs">
				 					<li><i class="la la-map-marker"></i> {{ $job->company->location }}</li>
				 					<li><i class="la la-money"></i> Type : <span>@if($job->type == 1)  Full Time @elseif($job->type == 2) Part Time  @elseif($job->type == 3) Freelance @elseif($job->type == 4) Internship @endif</span></li>
                                     <li><i class="la la-calendar-o"></i> Post Date: {{ date("Y M d",strtotime($job->created_at)) }}</li>
                                     <li><i class="la la-eye"></i> Views {{ $job->viewed }}</li>
				 				</ul>
				 			</div><!-- Job Head -->
				 			<div class="job-details">
                                 <h3>Job Description</h3>
                                 {!! $job->body !!}
				 			</div>
				 			<div class="job-overview">
					 			<h3>Job Overview</h3>
					 			<ul>
					 				<li><i class="la la-money"></i><h3>Finance</h3><span>@if($job->paid == 1) Paid @else Not Paid @endif</span></li>
					 				<li><i class="la la-thumb-tack"></i><h3>Position</h3><span>{{ $job->position }}</span></li>
					 				<li><i class="la la-puzzle-piece"></i><h3>Category</h3><span>{{ $job->category->title }}</span></li>
					 				<li><i class="la la-shield"></i><h3>Experience</h3><span>{{ $job->experience }}</span></li>
					 				<li><i class="la la-line-chart "></i><h3>Job Type </h3><span>@if($job->type == 1)  Full Time @elseif($job->type == 2) Part Time  @elseif($job->type == 3) Freelance @elseif($job->type == 4) Internship @endif</span></li>
					 			</ul>
					 		</div><!-- Job Overview -->
				 			<div class="share-bar">
				 				<!--<span>Share</span><a href="#" title="" class="share-fb"><i class="fa fa-facebook"></i></a>-->
				 				<!--<a href="#" title="" class="share-twitter"><i class="fa fa-twitter"></i></a>-->
				 			
				 			        <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3&appId=1808033569436858&autoLogAppEvents=1"></script>

        <div class="fb-share-button" data-href="{{ url()->current() }}" data-layout="button" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fcareerk.co%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share Job To Facebook</a></div>
</div>
				 		</div>
                     </div>
				 	</div>
				 	<div class="col-lg-4 column">
				 		<div class="job-single-head style2">
			 				 <img style="min-width: 100px;height: 190px;width: 190px;" src="{{ asset('/images/' . $job->company->avatar) }}" alt="{{ $job->company->title }}" style="max-width: 100px;"/>
			 				<div class="job-head-info">
			 					<h4>{{ $job->company->title }}</h4>
			 					<span>{{ $job->company->location }}</span>
			 					<p><i class="la la-phone"></i> {{ $job->company->mobile }}</p>
                                 <p><i class="la la-envelope-o"></i> {{ $job->company->email }}</p>

                             </div>
@php
            if (Auth::check()){

                   if(is_null($job->link)){
                    @endphp


                        <a href="" title="" class="apply-job-btn" onclick="event.preventDefault();
                        document.getElementById('apply').submit();">
                        <i class="la la-paper-plane"></i>Apply for job</a>

          <form id="apply" action="{{ route('apply.store') }}" method="POST" style="display: none;">
                  @csrf
                  <input type="text" value="{{ $job->id }}" name="job_id">
              </form>

              @php }else{  @endphp
                    <a href="{{ $job->link }}" title="" target="_blank" class="apply-job-btn"><i class="la la-paper-plane"></i>Apply for job</a>

                    @php  }

        }else{  @endphp

                             <a href="{{ route('login') }}" title="" class="apply-job-btn"><i class="la la-paper-plane"></i>Apply for job</a>
@php }
          @endphp
			 				<a href="{{ route('company.show', $job->company_id) }}" title="" class="viewall-jobs">View Company</a>
			 			</div><!-- Job Head -->
				 	</div>
				</div>
			</div>
		</div>
	</section>

@endsection