routes/web.php
<?php


//====================================================================================
//
//  ##      ##  #####  #####         #####     #####   ##   ##  ######  #####   ####
//  ##      ##  ##     ##  ##        ##  ##   ##   ##  ##   ##    ##    ##     ##
//  ##  ##  ##  #####  #####         #####    ##   ##  ##   ##    ##    #####   ###
//  ##  ##  ##  ##     ##  ##        ##  ##   ##   ##  ##   ##    ##    ##        ##
//   ###  ###   #####  #####         ##   ##   #####    #####     ##    #####  ####
//
//====================================================================================



//=======================================================
//
//   ####    ###    #####    #####  #####  #####    ##  ##
//  ##      ## ##   ##  ##   ##     ##     ##  ##   ## ##
//  ##     ##   ##  #####    #####  #####  #####    ####
//  ##     #######  ##  ##   ##     ##     ##  ##   ## ##
//   ####  ##   ##  ##   ##  #####  #####  ##   ##  ##  ##
//
//=========================================================




Route::get('/', 'Website\HomeController@index');

Route::resource('contact', 'Website\ContactController');

Route::get('/about', 'Website\HomeController@about');

Route::resource('blog', 'Website\BlogController');

Route::resource('job', 'Website\JobController');

Route::resource('profile', 'Website\ProfileController')->middleware(['auth', 'Student']);

Route::get('\profile/changePassword', function() {


    dd('this is right');
});

Route::get('/profile@changePassword', 'Website\ProfileController@changPassword')->middleware(['auth', 'Student']);

Route::resource('candidates', 'Website\CandidatesController');

Route::resource('company', 'Website\CompanyController');

Route::resource('category', 'Website\CategoryController');

Route::resource('apply', 'Website\ApplyController')->middleware(['auth', 'Student']);

Route::post('search', 'Website\ApplyController@search')->name('search');

Route::resource('comment', 'Website\CommentController');

Auth::routes();

app/Http/Controllers/Dashboard/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.profile.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);


        $request->validate([

            'name'     => 'required|string | min:5',
            'email'     => 'required|email',
            'phone'     => 'required| min:5',

        ]);


        $input = $request->all();

        $file = $request->file('avatar');

        $file = $request->file('avatar');


       if($file){

        $fileName = $file->getClientOriginalName();

        $fileName = uniqid() . $fileName;

        $file->move('images/', $fileName);

        $input['avatar'] = $fileName;


       }else {

        $input['avatar'] = $user->avatar;

       }

       if($request->has('password')){


        $input['password'] = bcrypt($request->password);

       }else{

        $input['password'] = $user->password;
       }


       $user = User::findOrFail($id)->update($input);


       session()->flash('message', 'Profile Updated Successfully');

       return redirect('dashboard/profile');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Website/ApplyController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Apply;
use Auth;
use App\Jobs;

class ApplyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'job_id'     => 'required|integer',
        ]);

        $data = $request->all();

        $data['user_id'] = Auth::user()->id;

        $exist = Apply::where([
            ['job_id', '=', $request->job_id],
            ['user_id', '=', $data['user_id']]
            
            ])->count();

        if($exist > 0){

            
       session()->flash('message', 'Job Already Applied');

       return redirect('job');

        }else{

        Apply::create($data);

        session()->flash('message', 'You Applied For The Job');

        return redirect('job');

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


public function search(Request $request) {

   $location = $request->search;

   $jobs = Jobs::where('title', '=',  $location);

  return view('website.search', compact('jobs'));




//   if(!empty($request->search)){
//     $searchFields = ['title','content','author_name','category_name'];
//     $query->where(function($query) use($request, $searchFields){
//       $searchWildcard = '%' . $request->search . '%';
//       foreach($searchFields as $field){
//         $query->orWhere($field, 'LIKE', $searchWildcard);
//       }
//     });
//   }




}

}

app/Http/Controllers/Website/BlogController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Blog;
use App\Comments;
class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::latest()->paginate(9);

        return view('website.blog.index', compact("blogs"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $recents = Blog::where('id', '!=', $id)->get();

        $blog = Blog::findOrFail($id);

        $comments = Comments::where('blog_id', $id)->get();

        return view('website.blog.show', compact("blog", "recents", 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Website/CandidatesController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Auth;
class CandidatesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
$students = User::where('role_id', '2')->latest()->paginate(8);;

return view('website.students.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $user = User::findOrFail($id);

        return view('website.students.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

app/Http/Controllers/Website/CategoryController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
use App\Jobs;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->paginate(16);;


        return view('website.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findOrFail($id);

        return view('website.category.show', compact('category'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Website/CommentController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Notifications\newComment;
use App\User;
use Illuminate\Support\Facades\Auth;
use App\Comments;
class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // $user = User::find(1);

        // $user->notify(new newComment);
        $request->validate([

        'blog_id'     => 'required',
    ]);


    $input = $request->all();


   $user = Auth::user()->id;

   $comment = Comments::create([

    'blog_id' => $request['blog_id'],
    'user_id' => $user,
    'body' => $request['body']

   ]);

   session()->flash('message', 'Comment Added Successfully');

   return redirect()->back();



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Website/CompanyController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Company;
use App\Jobs;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::latest()->paginate(9);;

        return view('website.company.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::findOrFail($id);

        $jobsCount = Jobs::where("company_id", $id)->count();

        $jobs = Jobs::where('company_id', $id)->get();

        return view('website.company.show', compact('company', 'jobs', 'jobsCount'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/website/profile/changepassword.blade.php
@extends('layouts.website')

@section('content')

	<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url(images/resource/mslider1.jpg) repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax"></div><!-- PARALLAX BACKGROUND IMAGE -->
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header">
							<h3>Change Your Password</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="block no-padding">
			<div class="container">
				 <div class="row no-gape">


                        <aside class="col-lg-3 column border-right">
                                <div class="widget">
                                    <div class="tree_widget-sec">
                                        <ul>
                                            <li><a href="{{ route('profile.index') }}" title=""><i class="la la-file-text"></i>My Profile</a></li>
                                           <li><a href="{{ asset('images/' . Auth::user()->cv) }}" target="_blank" title=""><i class="la la-briefcase"></i>My Resume</a></li>
                                           <li><a class="view-resume-list" title=""><i class="la la-paper-plane"></i>Applied Job</a></li>
                                           <li><a href="{{ route("profile.edit" , Auth::user()->id)}}" title=""><i class="la la-file-text"></i> Edit Profile</a></li>
                                           <li><a href="{{ route('profile.show', Auth::user()->id )}}" title=""><i class="la la-flash"></i>Change Password</a></li>
                                           <li class="signup-popup">
                                                <a title=""href="{{ route('logout') }}"
                                                onclick="event.preventDefault();
                                                              document.getElementById('logout-form').submit();"><i class="la la-unlink"></i>Sign Out</a>
                                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                        @csrf
                                                    </form>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="widget">
                                    <div class="skill-perc">
                                        <h3>Profile Progress </h3>
                                        <div class="skills-bar">
                                            <span>85%</span>
                                            <div
                                                class="second circle"
                                                data-size="155"
                                                data-thickness="60">
                                           </div>
                                        </div>
                                    </div>
                                </div>
                            </aside>


				 	<div class="col-lg-9 column">
				 		<div class="padding-left">
					 		<div class="manage-jobs-sec">
					 			<h3>Change Password</h3>
						 		<div class="change-password">
						 			<form method="post" action="{{ route('profile.store') }}">
                                         @csrf
						 				<div class="row">
						 					<div class="col-lg-6">
						 						<span class="pf-title">Old Password</span>
						 						<div class="pf-field">
						 							<input type="password" name="old_password" required />
						 						</div>
						 						<span class="pf-title">New Password</span>
						 						<div class="pf-field">
						 							<input type="password" name="password" required/>
						 						</div>
						 						<span class="pf-title">Confirm Password</span>
						 						<div class="pf-field">
						 							<input type="password" name="password_confirmation" />
						 						</div>
						 						<button type="submit">Update</button>
						 					</div>
						 					<div class="col-lg-6">
						 						<i class="la la-key big-icon"></i>
						 					</div>
						 				</div>
						 			</form>
						 		</div>
					 		</div>
					 	</div>
					</div>
				 </div>
			</div>
		</div>
	</section>
</div>


@include('partials._errors')
@endsection()

resources/views/website/profile/index.blade.php
@extends('layouts.website')

@section('content')

	<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url({{ asset('images/resource/mslider1.jpg') }} repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax"></div><!-- PARALLAX BACKGROUND IMAGE -->
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header">
							<h3>Welcome {{ Auth::user()->name }}</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="block no-padding">
			<div class="container">
				 <div class="row no-gape">

				 	<aside class="col-lg-3 column border-right">
				 		<div class="widget">
				 			<div class="tree_widget-sec">
				 				<ul>
				 					<li><a href="{{ route('profile.index') }}" title=""><i class="la la-file-text"></i>My Profile</a></li>
									<li><a href="{{ asset('images/' . Auth::user()->cv) }}" target="_blank" title=""><i class="la la-briefcase"></i>My Resume</a></li>
									<li><a class="view-resume-list" title=""><i class="la la-paper-plane"></i>Applied Job</a></li>
									<li><a href="{{ route("profile.edit" , Auth::user()->id)}}" title=""><i class="la la-file-text"></i> Edit Profile</a></li>
									<li><a href="{{ route('profile.show', Auth::user()->id )}}" title=""><i class="la la-flash"></i>Change Password</a></li>
                                    <li class="signup-popup">
                                            <a title=""href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                          document.getElementById('logout-form').submit();"><i class="la la-unlink"></i>Sign Out</a>
                                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                    @csrf
                                                </form>
                                        </li>
				 				</ul>
				 			</div>
				 		</div>
				 		<div class="widget">
				 			<div class="skill-perc">
				 				<h3>Profile Progress </h3>
				 				<div class="skills-bar">
				 					<span>85%</span>
				 					<div
				 						class="second circle"
				 						data-size="155"
				 						data-thickness="60">
								    </div>
				 				</div>
				 			</div>
				 		</div>
                     </aside>


                     <div class="col-lg-9 column">
				 		<div class="padding-left">
					 		<div class="manage-jobs-sec">

                                    <div class="edu-history-sec" style="padding-top: 28px;">
                                            <div class="edu-history">
                                               <img style="width: 100px;height: 100px;border-radius: 50%;border: 4px solid #8b91dd;" src="{{ asset('images/' . Auth::user()->avatar) }}"
                                                <div class="edu-hisinfo">
                                                    <div class="student-info" style="display: inline-block;">
                                                    <h3 style="margin-top: 10px;text-transform: capitalize;">{{ Auth::user()->name }}</h3>
                                                    <h6>{{ Auth::user()->email }}</h6>
                                                    <h6>{{ Auth::user()->phone }}</h6>
                                                    <h6>{{ Auth::user()->career }}</h6>

                                                    <p style="color:#8b91dd"> Contact Information Are @if(Auth::user()->public == 1 )
                                                        Public
                                                        @else
                                                        Private
                                                        @endif
                                                    </p>
                                                </div>
                                            </div>
                                        </div>

						 		<div class="cat-sec">
									<div class="row no-gape">

										<div class="col-lg-4 col-md-4 col-sm-12">
											<div class="p-category view-resume-list">
												<a href="#" title="">
													<i class="la la-briefcase"></i>
													<span>Applied Job</span>
													<p> {{ $appliedCount }} Applications</p>
												</a>
											</div>
										</div>
										<div class="col-lg-4 col-md-4 col-sm-12">
											<div class="p-category">
												<a href="{{ asset('images/' . Auth::user()->cv) }}" target="_blank" title="">
													<i class="la la-file-text "></i>
													<span>My CV</span>
													<p>View My CV</p>
												</a>
											</div>
                                        </div>

                                        <div class="col-lg-4 col-md-4 col-sm-12">
											<div class="p-category follow-companies-popup">
												<a href="#" title="">
													<i class="la la-envelope"></i>
													<span>Messages</span>
													<p>0 New Messages </p>
												</a>
											</div>
										</div>
									</div>
                                </div>

								<div class="cat-sec">


				 		<div class="padding-left">
					 		<div class="manage-jobs-sec">

		 						<div class="border-title"><h3>Professional Skills</h3></div>
		 						<div class="edu-history-sec">
		 							<div class="edu-history style2">
		 								<i></i>
		 								<div class="edu-hisinfo">
		 									<h3>About</h3>
                                             <p>{{ Auth::user()->body }}</p>
		 								</div>
		 							</div>
		 							<div class="edu-history style2">
		 								<i></i>
		 								<div class="edu-hisinfo">
		 									<h3> 	Experience </h3>
                                             <p>{{ Auth::user()->experience  }}</p>
		 								</div>
		 							</div>
		 							<div class="edu-history style2">
		 								<i></i>
		 								<div class="edu-hisinfo">
                                             <h3>Education</h3>

                                             <p>{{ Auth::user()->education  }}</p>
		 								</div>

		 							</div>
		 						</div>
					 		</div>
                         </div>

					</div>
				 </div>
			</div>
		</div>
	</section>



								</div>
					 		</div>
					 	</div>
					</div>
				 </div>
			</div>
		</div>
	</section>

</div>


<div class="view-resumesec">
	<div class="view-resumes">
		<span class="close-resume-popup"><i class="la la-close"></i></span>
        <h3>You applied for this jobs .</h3>

        @forelse ($applied as $item)

		<div class="job-listing wtabs" style="width: 50%;">
			<div class="job-title-sec">
				<div class="c-logo"> <img src="{{ asset('images/' . $item->avatar) }}" alt="" style="width: 100px;height: 100px;max-height: 100px;border-radius: 50%;min-height: 100px;margin-top: -21px;" /> </div>
				<h3><a href="{{ route('job.show', $item->id) }}" title="">{{ $item->title }}</a></h3>
				<span>{{ $item->position }}</span>
			</div>
        </div>
        @empty
           <h5> You Didnt Apply For Any Jobs </h5>
        @endforelse


	</div>
</div>

<div class="follow-companiesec">
	<div class="follow-companies">
		<span class="close-follow-company"><i class="la la-close"></i></span>
		<h3>Messages .</h3>
		<ul id="scrollbar">

	<h4 class="text-danger text-center"> You Have No Messages </h4>

		</ul>
	</div>
</div>



@endsection()