routes/web.php
<?php


//====================================================================================
//
//  ##      ##  #####  #####         #####     #####   ##   ##  ######  #####   ####
//  ##      ##  ##     ##  ##        ##  ##   ##   ##  ##   ##    ##    ##     ##
//  ##  ##  ##  #####  #####         #####    ##   ##  ##   ##    ##    #####   ###
//  ##  ##  ##  ##     ##  ##        ##  ##   ##   ##  ##   ##    ##    ##        ##
//   ###  ###   #####  #####         ##   ##   #####    #####     ##    #####  ####
//
//====================================================================================



//=======================================================
//
//   ####    ###    #####    #####  #####  #####    ##  ##
//  ##      ## ##   ##  ##   ##     ##     ##  ##   ## ##
//  ##     ##   ##  #####    #####  #####  #####    ####
//  ##     #######  ##  ##   ##     ##     ##  ##   ## ##
//   ####  ##   ##  ##   ##  #####  #####  ##   ##  ##  ##
//
//=========================================================




Route::get('/', 'Website\HomeController@index');

Route::resource('contact', 'Website\ContactController');

Route::get('/about', 'Website\HomeController@about');

Route::resource('blog', 'Website\BlogController');

Route::resource('job', 'Website\JobController');

Route::resource('profile', 'Website\ProfileController')->middleware(['auth', 'Student']);

Route::get('\profile/changePassword', function() {


    dd('this is right');
});

Route::get('/profile@changePassword', 'Website\ProfileController@changPassword')->middleware(['auth', 'Student']);

Route::resource('candidates', 'Website\CandidatesController');

Route::resource('company', 'Website\CompanyController');

Route::resource('category', 'Website\CategoryController');

Route::resource('apply', 'Website\ApplyController')->middleware(['auth', 'Student']);

Route::post('search', 'Website\ApplyController@search')->name('search');

Route::resource('comment', 'Website\CommentController');

Auth::routes();

app/Comments.php
<?php

namespace App;
use App\User;
use App\Blog;
use Illuminate\Database\Eloquent\Model;

class Comments extends Model
{


    protected $guarded =[];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function blog()
    {
        return $this->belongsTo(Blog::class);
    }

}

app/Http/Controllers/Dashboard/CommentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Comments;
class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $comments  = Comments::latest()->get();

        return view('admin.comments.index', compact("comments"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Comments::findOrFail($id)->delete();

        session()->flash('message', 'Comment Deleted Successfully');

        return redirect('dashboard/comment');
    }
}

app/Http/Controllers/Website/CommentController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Notifications\newComment;
use App\User;
use Illuminate\Support\Facades\Auth;
use App\Comments;
class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // $user = User::find(1);

        // $user->notify(new newComment);
        $request->validate([

        'blog_id'     => 'required',
    ]);


    $input = $request->all();


   $user = Auth::user()->id;

   $comment = Comments::create([

    'blog_id' => $request['blog_id'],
    'user_id' => $user,
    'body' => $request['body']

   ]);

   session()->flash('message', 'Comment Added Successfully');

   return redirect()->back();



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/comments/create.blade.php
@extends('layouts.admin')
@section('content')

  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumb-->
     <div class="row pt-2 pb-2">
        <div class="col-sm-9">
		    <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route ('dashboard.blog.index')}}">Blogs</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add New Blog</li>
         </ol>
	   </div>
     </div>

    <!-- End Breadcrumb-->

    <div class="row">
        <div class="col-lg-12">

   <div class="card">
       <div class="card-body">
       <div class="card-title">Add New Blog</div>
       <hr>
        <form method="POST" action="{{ route('dashboard.blog.store') }}" enctype="multipart/form-data">

            @csrf

<div class="row">

<div class="col-md-6">
       <div class="form-group row">
        <label for="input-26" class="col-sm-3 col-form-label">Blog Title</label>
        <div class="col-sm-9">
        <input required="required" type="text" value="{{ old('title') }}" class="form-control form-control-rounded @error('title') is-invalid @enderror" id="input-26" placeholder="Enter Blog Title" name="title">
        </div>
      </div>
</div>

 <div class="col-md-6">
        <div class="form-group row">
                <label for="input-30" class="col-sm-3 col-form-label">Blog Photo</label>
                <div class="col-sm-9">
                <input type="file" class="form-control form-control-rounded @error('logo') is-invalid @enderror" id="input-30" required="required" name="avatar">
                </div>
              </div>
 </div>
</div>

        <div class="card-header text-uppercase"> Blog Descreption </div>
        <div class="card-body">
         <textarea name="body" id="summernoteEditor" style="display: none;" class="@error('body') is-invalid @enderror" required="required"></textarea



      <div class="form-group row">
        <label class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="form-footer">
                <button type="reset" class="btn btn-danger"><i class="fa fa-times"></i> CANCEL</button>
                <button type="submit" class="btn btn-success"><i class="fa fa-check-square-o"></i> SAVE</button>
            </div>
        </div>
      </div>
      </form>
     </div>
     </div>

        </div>
      </div>

    </div>
    <!-- End container-fluid-->

    </div><!--End content-wrapper-->
   <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->


    @include('partials._errors')

  </div><!--End wrapper-->


@endsection

resources/views/admin/comments/edit.blade.php
@extends('layouts.admin')
@section('content')

  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumb-->
     <div class="row pt-2 pb-2">
        <div class="col-sm-9">
		    <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route ('dashboard.blog.index')}}">Blogs</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit {{ $blog->title  }}</li>
         </ol>
	   </div>
     </div>

    <!-- End Breadcrumb-->

    <div class="row">
        <div class="col-lg-12">

   <div class="card">
       <div class="card-body">
       <div class="card-title">Edit {{ $blog->title  }}</div>
       <hr>
        <form method="POST" action="{{ route('dashboard.blog.update', $blog->id ) }}" enctype="multipart/form-data">



            @method('PUT')

<div class="row">

<div class="col-md-6">
       <div class="form-group row">
        <label for="input-26" class="col-sm-3 col-form-label">Blog Title</label>
        <div class="col-sm-9">
        <input required="required" type="text" value="{{ $blog->title }}" class="form-control form-control-rounded @error('title') is-invalid @enderror" id="input-26" placeholder="Enter Blog Title" name="title">
        </div>
      </div>
</div>

 <div class="col-md-6">
        <div class="form-group row">
                <label for="input-30" class="col-sm-3 col-form-label">Blog Photo</label>
                <div class="col-sm-9">
                <input type="file" class="form-control form-control-rounded @error('logo') is-invalid @enderror" id="input-30"  name="avatar">
                </div>
              </div>
 </div>
</div>

        <div class="card-header text-uppercase"> Blog Descreption </div>
        <div class="card-body">
         <textarea name="body" id="summernoteEditor" style="display: none;" class="@error('body') is-invalid @enderror" required="required">{{ $blog->body }}</textarea



      <div class="form-group row">
        <label class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="form-footer">
                <button type="reset" class="btn btn-danger"><i class="fa fa-times"></i> CANCEL</button>
                <button type="submit" class="btn btn-success"><i class="fa fa-check-square-o"></i> SAVE</button>
            </div>
        </div>
      </div>
      </form>
     </div>
     </div>

        </div>
      </div>

    </div>
    <!-- End container-fluid-->

    </div><!--End content-wrapper-->
   <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->


    @include('partials._errors')

  </div><!--End wrapper-->


@endsection

resources/views/admin/comments/index.blade.php
@extends('layouts.admin')
@section('content')


  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumb-->
     <div class="row pt-2 pb-2">
        <div class="col-sm-9">
		    <h4 class="page-title">Blogs Comments </h4>
	   </div>
     </div>
    <!-- End Breadcrumb-->

      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
              <table id="example" class="table table-bordered">
                <thead>
                    <tr>
                         <th>ID</th>
                        <th>Name</th>
                        <th>Blog</th>
                        <th> Comment </th>
                        <th> Date </th>
                        <th>Control</th>

                    </tr>
                </thead>
                <tbody>

                    @foreach ($comments as $comment)

                    <tr>
                        <td>{{ $comment->id }}</td>
                        <td>{{ $comment->user->name }}</td>
                        <td>{{ $comment->blog->title }}</td>
                        <td>{{ $comment->body }}</td>
                        <td>{{ date("Y M d", strtotime($comment->created_at)) }}</td>

                        <td><div class="btn-group m-1">
                            <form method="post" action="{{ route('dashboard.comment.destroy', $comment->id ) }}">

                                @method('DELETE')
                                @csrf

                                <button class="delete_btn btn btn-light waves-effect waves-light"> <i class="fa fa fa-trash-o"></i> </button>
                             </form>
                         </div></td>
                    </tr>

                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Blog</th>
                        <th> Comment </th>
                        <th> Date </th>
                        <th>Control</th>
                    </tr>
                </tfoot>
            </table>
            </div>
            </div>
          </div>
        </div>
      </div><!-- End Row-->

    </div>
    <!-- End container-fluid-->

    </div><!--End content-wrapper-->
   <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->

  </div><!--End wrapper-->

@endsection