routes/web.php
<?php


//====================================================================================
//
//  ##      ##  #####  #####         #####     #####   ##   ##  ######  #####   ####
//  ##      ##  ##     ##  ##        ##  ##   ##   ##  ##   ##    ##    ##     ##
//  ##  ##  ##  #####  #####         #####    ##   ##  ##   ##    ##    #####   ###
//  ##  ##  ##  ##     ##  ##        ##  ##   ##   ##  ##   ##    ##    ##        ##
//   ###  ###   #####  #####         ##   ##   #####    #####     ##    #####  ####
//
//====================================================================================



//=======================================================
//
//   ####    ###    #####    #####  #####  #####    ##  ##
//  ##      ## ##   ##  ##   ##     ##     ##  ##   ## ##
//  ##     ##   ##  #####    #####  #####  #####    ####
//  ##     #######  ##  ##   ##     ##     ##  ##   ## ##
//   ####  ##   ##  ##   ##  #####  #####  ##   ##  ##  ##
//
//=========================================================




Route::get('/', 'Website\HomeController@index');

Route::resource('contact', 'Website\ContactController');

Route::get('/about', 'Website\HomeController@about');

Route::resource('blog', 'Website\BlogController');

Route::resource('job', 'Website\JobController');

Route::resource('profile', 'Website\ProfileController')->middleware(['auth', 'Student']);

Route::get('\profile/changePassword', function() {


    dd('this is right');
});

Route::get('/profile@changePassword', 'Website\ProfileController@changPassword')->middleware(['auth', 'Student']);

Route::resource('candidates', 'Website\CandidatesController');

Route::resource('company', 'Website\CompanyController');

Route::resource('category', 'Website\CategoryController');

Route::resource('apply', 'Website\ApplyController')->middleware(['auth', 'Student']);

Route::post('search', 'Website\ApplyController@search')->name('search');

Route::resource('comment', 'Website\CommentController');

Auth::routes();

app/Apply.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Jobs;
class Apply extends Model
{
    protected $guarded = [];


    public function user()
    {
        return $this->belongsTo(User::class);
    }


    public function job()
    {
        return $this->belongsTo(Jobs::class);
    }


}

app/Http/Controllers/Dashboard/ApplyController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Apply;
use App\Jobs;
class ApplyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $applies  = Apply::latest()->get();

        return view('admin.apply.index', compact("applies"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Website/ApplyController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Apply;
use Auth;
use App\Jobs;

class ApplyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'job_id'     => 'required|integer',
        ]);

        $data = $request->all();

        $data['user_id'] = Auth::user()->id;

        $exist = Apply::where([
            ['job_id', '=', $request->job_id],
            ['user_id', '=', $data['user_id']]
            
            ])->count();

        if($exist > 0){

            
       session()->flash('message', 'Job Already Applied');

       return redirect('job');

        }else{

        Apply::create($data);

        session()->flash('message', 'You Applied For The Job');

        return redirect('job');

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


public function search(Request $request) {

   $location = $request->search;

   $jobs = Jobs::where('title', '=',  $location);

  return view('website.search', compact('jobs'));




//   if(!empty($request->search)){
//     $searchFields = ['title','content','author_name','category_name'];
//     $query->where(function($query) use($request, $searchFields){
//       $searchWildcard = '%' . $request->search . '%';
//       foreach($searchFields as $field){
//         $query->orWhere($field, 'LIKE', $searchWildcard);
//       }
//     });
//   }




}

}

resources/views/admin/apply/index.blade.php
@extends('layouts.admin')
@section('content')


  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumb-->
     <div class="row pt-2 pb-2">
        <div class="col-sm-9">
		    <h4 class="page-title">Applied appliess</h4>
	   </div>
     </div>
    <!-- End Breadcrumb-->

      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
              <table id="example" class="table table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Avatar</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Job</th>
                        <th> View Profile </th>
                        <th>Apply Date</th>
                        <th>Controll</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach ($applies as $applies)

                    <tr>
                        <td>{{ $applies->user->name }}</td>
                        <td><img src="{{asset('images/'. $applies->avatar) }}" class="company_photo"> </td>
                        <td>{{ $applies->user->email}}</td>
                        <td>{{ $applies->user->phone}}</td>
                        <td>{{ $applies->job->title }}</td>
                       <th> <a href="{{ route('candidates.show', $applies->user->id)}}" target="_blank"> <i style="text-align: center;font-size: 42px;display: block;" class="fa fa-eye"></i> </a></th>
                        <td>{{ date("Y M d", strtotime($applies->created_at)) }}</td>
                        <td><div class="btn-group m-1">
                            <form method="post" action="{{ route('dashboard.apply.destroy', $applies->id ) }}">
                                @method('DELETE')
                                @csrf
                                <button class="delete_btn btn btn-light waves-effect waves-light"> <i class="fa fa fa-trash-o"></i> </button>
                             </form>
                         </div></td>

                    </tr>

                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Avatar</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Job</th>
                        <th> View Profile </th>
                        <th>Apply Date</th>
                        <th>Controll</th>
                    </tr>
                </tfoot>
            </table>
            </div>
            </div>
          </div>
        </div>
      </div><!-- End Row-->

    </div>
    <!-- End container-fluid-->

    </div><!--End content-wrapper-->
   <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->



  </div><!--End wrapper-->



@endsection